### ISSUE TITLE
The repository structure is problematic when customizing

### ISSUE THREAD

**Issue by niklas88** [enclustra-bsp/bsp-xilinx-container#1]
When I want to customize e.g the Linux kernel say by adding a devicetree including custom IP things would be easier if this were part of bsp-xilinx. As it stands I not only need a custom bsp-xilinx repository to hold custom target definitions plus the customized kernel repository but also a custom bsp-xilinx-container repository so that I can point the submodule xilinx-linux at my custom tree.

Also as the build-scripts update the submodules in this repository outside the submodule mechanism e.g. when using the 1.3 branch they are often not at the revision pointed to by the submodules even if unchanged.

**Comment by tgorochowik** [comment]
Hello Niklas,

thanks for the suggestion.

The idea however is to be able to quickly change 'everything' simply by changing the container.
With this approach you can prepare a few containers and ship them to different groups of users.

We might want to reconsider it in the future, but we want to keep it the way it is for the time being.

If you want to quickly use the build system for your purposes you can just enter the source directory (e.g. `cd sources/xilinx-linux/`) and do your work over there.

If you want to ship it however, then creating a container is indeed necessary.

**Comment by tgorochowik** [comment]
The container repos are not used anymore, I guess we can close this one. Thanks again!
